from sqlalchemy.orm import Session
from datetime import datetime, timezone
from typing import Dict, Any, List, Union
from app.models.all_models import TelemetryRecord, RailwayNode, ThreatEvent, Corridor
from app.services.anomaly_service import anomaly_service
from app.services.incident_service import IncidentService
from app.services.realtime_service import realtime_broadcaster
from app.services.ledger_service import LedgerService
from app.services.audit_service import AuditService

class TelemetryService:
    @staticmethod
    async def ingest_packet(db: Session, packet: Any) -> Dict[str, Any]:
        data = packet.dict() if hasattr(packet, "dict") else dict(packet)
        return await TelemetryService.ingest_telemetry(db, data)

    @staticmethod
    async def ingest_telemetry(db: Session, data: Dict[str, Any]) -> Dict[str, Any]:
        node_id = data.get("node_id", "DL-01")
        cpu = float(data.get("cpu", 35.0))
        memory = float(data.get("memory", 55.0))
        temperature = float(data.get("temperature", 26.5))
        vibration = float(data.get("vibration", 0.25))
        acoustic = float(data.get("acoustic", 45.0))
        net_in = int(data.get("network_in", 1200))
        net_out = int(data.get("network_out", 850))

        # 1. Store Record
        record = TelemetryRecord(
            node_id=node_id,
            cpu=cpu,
            memory=memory,
            temperature=temperature,
            vibration=vibration,
            acoustic=acoustic,
            network_in=net_in,
            network_out=net_out,
            timestamp=datetime.now(timezone.utc)
        )
        db.add(record)

        # 2. Run Anomaly Pipeline
        analysis = anomaly_service.analyze_telemetry({
            "vibration": vibration,
            "acoustic": acoustic,
            "temperature": temperature,
            "cpu": cpu,
            "network_out": net_out
        })

        # 3. Update Node Status
        node = db.query(RailwayNode).filter(RailwayNode.node_id == node_id).first()
        if node:
            node.last_heartbeat = datetime.now(timezone.utc)
            node.health_score = max(0.0, 100.0 - analysis["score"])
            node.cpu_load = cpu
            node.temperature = temperature
            node.vibration = vibration
            if analysis["severity"] in ["CRITICAL", "HIGH"]:
                node.status = "Alert"
                node.threat_level = analysis["severity"]
            elif analysis["severity"] == "MEDIUM":
                node.status = "Caution"
                node.threat_level = "ELEVATED"
            else:
                node.status = "Normal"
                node.threat_level = "NORMAL"

        # 4. Handle Threat & Incident Creation
        new_threat = None
        new_incident = None
        if analysis["is_anomaly"]:
            now_str = datetime.now().strftime("%H:%M:%S")
            threat_id = f"THR-{int(datetime.now(timezone.utc).timestamp()*1000)}"
            location_str = f"Node {node_id}"
            if node:
                location_str = f"{node.name} ({node_id})"

            primary_reason = analysis["reasons"][0] if analysis["reasons"] else "Telemetry baseline deviation"
            new_threat = ThreatEvent(
                threat_id=threat_id,
                severity=analysis["severity"],
                location=location_str,
                event=primary_reason,
                category="PHYSICAL_DEFECT" if "vibration" in primary_reason.lower() or "acoustic" in primary_reason.lower() else "SECURITY",
                status="ACTIVE",
                score=analysis["score"],
                time_str=now_str,
                timestamp=datetime.now(timezone.utc)
            )
            db.add(new_threat)

            # Auto create incident if critical
            if analysis.get("trigger_incident", False):
                new_incident = await IncidentService.create_incident(
                    db=db,
                    title=f"Structural Anomaly: {primary_reason}",
                    severity=analysis["severity"],
                    location=location_str,
                    node_id=node_id,
                    description=f"Auto-generated by Telemetry Anomaly Pipeline. Anomaly score: {analysis['score']:.1f}/100.",
                    username="SYSTEM_ANOMALY_ENGINE"
                )

        db.commit()
        db.refresh(record)

        # 5. Broadcast Realtime Updates
        await realtime_broadcaster.broadcast("telemetry.updated", {
            "node_id": node_id,
            "cpu": cpu,
            "memory": memory,
            "temperature": temperature,
            "vibration": vibration,
            "network_in": net_in,
            "network_out": net_out,
            "status": node.status if node else "Normal",
            "health_score": node.health_score if node else 98.4
        })

        if new_threat:
            await realtime_broadcaster.broadcast("threat.created", {
                "id": new_threat.id,
                "threat_id": new_threat.threat_id,
                "severity": new_threat.severity,
                "location": new_threat.location,
                "event": new_threat.event,
                "description": new_threat.event,
                "category": new_threat.category,
                "status": new_threat.status,
                "time": new_threat.time_str
            })

        return {
            "record_id": record.id,
            "node_id": node_id,
            "analysis": analysis,
            "threat_created": new_threat.threat_id if new_threat else None,
            "incident_created": new_incident.incident_id if new_incident else None
        }

    @staticmethod
    def get_system_stats(db: Session) -> Dict[str, Any]:
        total_nodes = db.query(RailwayNode).count() or 25
        active_nodes = db.query(RailwayNode).filter(RailwayNode.status != "Offline").count() or 25
        unresolved_count = db.query(ThreatEvent).filter(ThreatEvent.severity.in_(["HIGH", "CRITICAL"]), ThreatEvent.status == "ACTIVE").count()

        nodes = db.query(RailwayNode).all()
        avg_health = 98.4
        if nodes:
            avg_health = round(sum(n.health_score for n in nodes) / len(nodes), 1)

        threat_level = "NORMAL"
        if unresolved_count > 2:
            threat_level = "CRITICAL"
        elif unresolved_count > 0:
            threat_level = "ELEVATED"

        return {
            "network_health": avg_health,
            "health_delta": "+0.2%",
            "active_corridors": 25,
            "total_corridors": 25,
            "freight_trains": 2840,
            "express_trains": 412,
            "unresolved_anomalies": unresolved_count,
            "mean_response_time": "4.2m",
            "response_delta": "-18%",
            "auto_dispatch_ms": 140,
            "uptime": "99.991%",
            "nodes_online": 412,
            "total_nodes": 412,
            "telemetry_latency_ms": 12,
            "tunnel_protocol": "AES-256 GCM",
            "threat_level": threat_level,
            "pkts_per_sec": 1240
        }

    get_dashboard_stats = get_system_stats
